### ISSUE TITLE
RCTJSONStringify() encountered the following error: Invalid number value (infinite) in JSON write on IOS

### ISSUE THREAD

**Issue by Waker777** [aws/amazon-ivs-react-native#5]
This error happen only with links which has a '.m3u8' 

This is test url stream video from example also produce this bug 
const URL =
  'https://fcc3ddae59ed.us-west-2.playback.live-video.net/api/video/v1/us-west-2.893648527354.channel.DmumNckWFTqz.m3u8';

How can i fix this? 

I use this player in react-native 0.64.2

**Comment by maxstoller** [comment]
Hi @Waker777, thanks for reporting this. We are taking a look and will get back to you here.

**Comment by Waker777** [comment]
@maxstoller  thank you..
I still try to fix this , so maybe this info you can help:
If try to running player from your example, from repository, all okay.. but i have notice , what you get this player from root directory of repo, if  to install the player from npm , then get this error.

**Comment by Waker777** [comment]
@maxstoller  Hi, can you please check PR ?  seems what this bug is already must be fixed

**Comment by maxstoller** [comment]
We are reviewing this PR now and will release it as soon as we can. I will respond here when it's out. Thanks!

**Comment by maxstoller** [comment]
@Waker777 This fix has been released as 1.0.1-beta. Thanks again for submitting this issue.
